;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	cua--prefix-override-handler
	end-of-visual-line
	kill-visual-line
	org-kill-line
	perl-electric-terminator
	python-backspace
	))

(setq mc/cmds-to-run-once
      '(
	end-of-buffer
	eval-print-last-sexp
	iswitchb-buffer
	suspend-frame
	))
